name: GitHub Actions Build
on:
   push:
       branches:
          - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install and Build
        run: |
          npm install
          npm run build
