name: Github Actions Demo
on:
   push:
     branches:
       - main
jobs:
  Test :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
            npm install
            npm run build
